format = """
$time\

[](color_yellow)\
$os\
$username\
[](bg:color_blue fg:color_yellow)\

$directory\
[](fg:color_blue bg:color_bg)\

$git_branch\
$git_status\

$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\

$line_break$character
"""

palette = 'ayu'

[palettes.ayu]
color_text = '#B3B1AD'
color_bg = '#0A0E14'
color_bgdim = '#00010A'
color_red = '#ff3333'
color_orange = '#FF8F40'
color_yellow = '#E6B450'
color_green = '#C2D94C'
color_blue = '#39BAE6'
color_cyan = '#95E6CB'
color_purple = '#CB9FF8'

[palettes.nightcity]
color_text = '#f9efc5'
color_bg = '#191b29'
color_bgdim = '#25272e'
color_red = '#ff5f3b'
color_orange = '#ff8f57'
color_yellow = '#ffb833'
color_green = '#9ea32a'
color_aqua = '#8db885'
color_blue = '#6e9685'
color_cyan = '#67c4bd'
color_purple = '#d9869e'
color_magenta = '#db5b8a'

[os]
disabled = false
style = "bg:color_yellow fg:color_bg"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[username]
show_always = true
style_user = "bg:color_yellow fg:color_bg"
style_root = "bg:color_yellow fg:color_bg"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Desktop" = "󰧨 "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
".config" =  " "
"~" = " "

[git_branch]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol $branch ](fg:color_purple bg:color_bg)]($style)'

[git_status]
style = "bg:color_bg"
format = '[[($all_status$ahead_behind )](fg:color_purple bg:color_bg)]($style)'

[nodejs]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[c]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[rust]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[golang]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[php]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[java]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[kotlin]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[haskell]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[python]
symbol = " "
style = "bg:color_bg"
format = '[[ $symbol( $version) ](fg:color_text bg:color_bg)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg"
format = '[[ $time ](fg:color_yellow bg:color_bg)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ](bold fg:color_green)'
error_symbol = '[ ](bold fg:color_red)'
vimcmd_symbol = '[ ](bold fg:color_green)'
vimcmd_replace_one_symbol = '[ ](bold fg:color_purple)'
vimcmd_replace_symbol = '[ ](bold fg:color_purple)'
vimcmd_visual_symbol = '[ ](bold fg:color_yellow)'
