-- require "plugin_config.colorscheme.colorbuddy"
-- require "plugin_config.colorscheme.vscodecolor"
-- require "plugin_config.colorscheme.tokyonight"
-- require "plugin_config.colorscheme.onedark"
-- require "plugin_config.colorscheme.catppuccin"
-- require "plugin_config.colorscheme.material"
require "plugin_config.colorscheme.colorscheme"
